
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TJ_Leather_Inventory_System.Model
{

using System;
    using System.Collections.Generic;
    
public partial class RawMaterialDetail
{

    public int RawMaterialDetailsID { get; set; }

    public Nullable<int> RawMaterialTypeID { get; set; }

    public Nullable<int> RawMaterialQuantity { get; set; }

    public Nullable<int> RawMaterialSupplierID { get; set; }

    public Nullable<System.DateTime> RawMaterialPurchseDate { get; set; }

    public Nullable<double> AmountPaid { get; set; }

    public Nullable<int> RawMaterialAmountGivenToLabourDept { get; set; }



    public virtual RawMaterialSupplier RawMaterialSupplier { get; set; }

    public virtual RawMaterialType RawMaterialType { get; set; }

}

}
