//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJ_Leather_Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public CustomerDetail()
        {
            this.CustomerOrderDetails = new HashSet<CustomerOrderDetail>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerEmail { get; set; }
        public Nullable<long> CustomerMobileNum { get; set; }
        public Nullable<long> CustomerTelephone { get; set; }
        public Nullable<long> CustomerFax { get; set; }
        public string CustomerWebsite { get; set; }
        public string Remarks { get; set; }
        public string PricingScheme { get; set; }
        public string PaymentTerms { get; set; }
        public string TaxingScheme { get; set; }
    
        public virtual ICollection<CustomerOrderDetail> CustomerOrderDetails { get; set; }
    }
}
