//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJ_Leather_Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderDetail
    {
        public int CustomerOrderDetailsID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> Paid { get; set; }
        public Nullable<double> RemainingBalance { get; set; }
        public Nullable<double> CreditBalance { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
    }
}
