//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJ_Leather_Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeDetail
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeCNIC { get; set; }
        public string EmployeeDesignation { get; set; }
        public Nullable<long> EmployeeMobileNumber { get; set; }
        public Nullable<long> EmployeeTelephoneNumber { get; set; }
        public string EmployeeEmailID { get; set; }
        public byte[] EmployeeImage { get; set; }
        public string EmployeePassword { get; set; }
    }
}
