//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJ_Leather_Inventory_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialSupplier
    {
        public RawMaterialSupplier()
        {
            this.RawMaterialDetails = new HashSet<RawMaterialDetail>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public Nullable<long> SuplierTelephone { get; set; }
        public Nullable<long> SupplierMobile { get; set; }
        public string SupplierCompanyName { get; set; }
        public string SupplierEmailAddress { get; set; }
        public Nullable<System.DateTime> SupplierRegisterDtae { get; set; }
    
        public virtual ICollection<RawMaterialDetail> RawMaterialDetails { get; set; }
    }
}
