//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJ_Leather_Inventory_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TJLeatherIvnetoryDBEntities : DbContext
    {
        public TJLeatherIvnetoryDBEntities()
            : base("name=TJLeatherIvnetoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerDetail> CustomerDetails { get; set; }
        public virtual DbSet<CustomerOrderDetail> CustomerOrderDetails { get; set; }
        public virtual DbSet<EmployeDetail> EmployeDetails { get; set; }
        public virtual DbSet<RawMaterialDetail> RawMaterialDetails { get; set; }
        public virtual DbSet<RawMaterialSupplier> RawMaterialSuppliers { get; set; }
        public virtual DbSet<RawMaterialType> RawMaterialTypes { get; set; }
    }
}
